name = "JsonGrinder"
uuid = "d201646e-a9c0-11e8-1063-23b139159713"
authors = ["pevnak <pevnak@gmail.com>", "Matej Racinsky <racinsky.matej@seznam.cz>"]
version = "2.2.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HierarchicalUtils = "f9ccea15-0695-44b9-8113-df7c26ae4fa9"
HttpCommon = "77172c1b-203f-54ac-aa54-3f1198fe9f90"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
Mill = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BSON = "^0.3.1"
DataStructures = "~0.17, ~0.18"
FillArrays = "~0.8, ~0.9, ~0.10, 0.11"
Flux = "^0.12"
HierarchicalUtils = "~1.9"
HttpCommon = "^0.5"
JSON = "~0.20, ~0.21"
LearnBase = "^0.4"
MLDataPattern = "^0.5"
Mill = "~2.5"
Mustache = "^1"
Setfield = "~0.6, ~0.7"
StatsBase = "^0.33"
ThreadTools = "^0.2"
Zygote = "^0.5.10, 0.6"
julia = "^1.5"
