[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ElectronDisplay = "d872a56f-244b-5cc9-b574-2017b5b909a8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JsonGrinder = "d201646e-a9c0-11e8-1063-23b139159713"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
Mill = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
PrintTypesTersely = "41b232b1-0de0-4a65-aab4-126884588aaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
